version: '3.8'

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.9.1
  platform: linux/arm64  # ✅ For Mac M1/M2
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__FERNET_KEY: dPz8OKcqqYUc9G9kzW4dHavmmFPvx3bDck8b9oPZtMI=
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW__LOGGING__LOGGING_LEVEL: 'INFO'
    PYTHONPATH: /opt/airflow/scripts:/opt/airflow/scripts/extraction_pipeline:/opt/airflow/scripts/LLMquery
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./scripts:/opt/airflow/scripts
    - ./data:/opt/airflow/data
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_started

services:
  postgres:
    image: postgres:13
    platform: linux/arm64
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 10
      timeout: 5s
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    platform: linux/arm64
    ports:
      - "6379:6379"

  airflow-init:
    <<: *airflow-common
    user: "0:0"
    entrypoint: >
      bash -c "
        echo 'Waiting for Postgres...';
        while ! pg_isready -h postgres -U airflow; do sleep 2; done;
        echo 'Initializing Airflow DB...';
        airflow db migrate;
        airflow users create \
          --username admin \
          --password admin \
          --firstname Kousik \
          --lastname Nandury \
          --role Admin \
          --email kousik@example.com || true;
        echo '✅ Initialization complete.';
      "

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8090:8080"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      retries: 5
      start_period: 20s

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    restart: always

volumes:
  postgres-db-volume:
